# Generated by Django 4.2.5 on 2023-09-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "peykhangApi",
            "0002_author_genre_book_isbn_book_summary_alter_book_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                help_text="Select a genre for this book", to="peykhangApi.genre"
            ),
        ),
    ]
