# Generated by Django 4.2.3 on 2023-09-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='label',
        ),
    ]
