# Generated by Django 4.2.3 on 2023-09-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0007_alter_book_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('french', 'French'), ('tibetan', 'Tibetan'), ('hindi', 'Hindi'), ('english', 'English'), ('mandarin', 'Mandarin'), ('spanish', 'Spanish')], default='tibetan', help_text='Selekc the book language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('non_fiction', 'Non Fiction'), ('fiction', 'Fiction')], default='fiction', help_text='Select the book category'),
        ),
    ]
