# Generated by Django 4.2.3 on 2023-09-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0008_book_language_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('italian', 'Italian'), ('english', 'English'), ('tibetan', 'Tibetan'), ('chinese', 'Chinese'), ('spanish', 'Spanish'), ('french', 'French')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
