# Generated by Django 4.2.3 on 2023-11-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0009_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover_url',
            field=models.TextField(help_text='Enter the AWS S3 Bucket uri that stores the book cover', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('tibetan', 'Tibetan'), ('spanish', 'Spanish'), ('chinese', 'Chinese'), ('french', 'French'), ('italian', 'Italian'), ('english', 'English'), ('hindi', 'Hindi')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
