# Generated by Django 4.2.3 on 2023-11-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0010_book_book_cover_url_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='summary',
            field=models.TextField(blank=True, help_text='Information about the author', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('french', 'French'), ('hindi', 'Hindi'), ('chinese', 'Chinese'), ('tibetan', 'Tibetan'), ('italian', 'Italian'), ('english', 'English'), ('spanish', 'Spanish')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
