# Generated by Django 4.2.3 on 2023-11-13 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0011_author_summary_alter_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('italian', 'Italian'), ('french', 'French'), ('chinese', 'Chinese'), ('spanish', 'Spanish'), ('tibetan', 'Tibetan')], default='tibetan', help_text='Selekc the book language'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(help_text='Select the publisher', null=True, on_delete=django.db.models.deletion.CASCADE, to='peykhangApi.publisher'),
        ),
    ]
