# Generated by Django 4.2.3 on 2023-11-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0012_publisher_alter_book_language_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('chinese', 'Chinese'), ('italian', 'Italian'), ('spanish', 'Spanish'), ('french', 'French'), ('hindi', 'Hindi'), ('tibetan', 'Tibetan'), ('english', 'English')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
