# Generated by Django 4.2.3 on 2023-11-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0015_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Book publication date', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('non_fiction', 'Non Fiction'), ('fiction', 'Fiction')], default='fiction', help_text='Select the book category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('tibetan', 'Tibetan'), ('chinese', 'Chinese'), ('spanish', 'Spanish'), ('english', 'English'), ('italian', 'Italian'), ('french', 'French'), ('hindi', 'Hindi')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
