# Generated by Django 4.2.3 on 2023-11-18 21:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0020_author_author_image_url_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rich_text_summary',
            field=ckeditor.fields.RichTextField(help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non Fiction')], default='fiction', help_text='Select the book category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('french', 'French'), ('english', 'English'), ('chinese', 'Chinese'), ('italian', 'Italian'), ('spanish', 'Spanish'), ('tibetan', 'Tibetan')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
