# Generated by Django 4.2.3 on 2023-11-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0021_book_rich_text_summary_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('non_fiction', 'Non Fiction'), ('fiction', 'Fiction')], default='fiction', help_text='Select the book category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('italian', 'Italian'), ('tibetan', 'Tibetan'), ('english', 'English'), ('chinese', 'Chinese'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('french', 'French')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
