# Generated by Django 4.2.3 on 2023-11-18 21:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0022_alter_book_category_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non Fiction')], default='fiction', help_text='Select the book category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('italian', 'Italian'), ('french', 'French'), ('tibetan', 'Tibetan'), ('spanish', 'Spanish'), ('english', 'English'), ('chinese', 'Chinese'), ('hindi', 'Hindi')], default='tibetan', help_text='Selekc the book language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rich_text_summary',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
