# Generated by Django 4.2.3 on 2023-11-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0023_alter_book_category_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('french', 'French'), ('spanish', 'Spanish'), ('tibetan', 'Tibetan'), ('hindi', 'Hindi'), ('chinese', 'Chinese'), ('italian', 'Italian')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
