# Generated by Django 4.2.3 on 2023-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0027_alter_book_language_alter_book_rich_text_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non Fiction')], default='fiction', help_text='Select the book category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('chinese', 'Chinese'), ('french', 'French'), ('english', 'English'), ('tibetan', 'Tibetan'), ('spanish', 'Spanish'), ('hindi', 'Hindi'), ('italian', 'Italian')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
