# Generated by Django 4.2.3 on 2023-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0028_alter_book_category_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', null=True, to='peykhangApi.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('es', 'Spanish'), ('en', 'English'), ('fr', 'French'), ('bo', 'Tibetan'), ('zh', 'Chinese'), ('it', 'Italian')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
