# Generated by Django 4.2.3 on 2023-12-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0029_alter_book_genre_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('bo', 'Tibetan'), ('es', 'Spanish'), ('zh', 'Chinese'), ('fr', 'French'), ('it', 'Italian')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
