# Generated by Django 4.2.3 on 2023-12-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0030_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('non_fiction', 'Non Fiction'), ('fiction', 'Fiction')], default='fiction', help_text='Select the book category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('it', 'Italian'), ('fr', 'French'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('bo', 'Tibetan')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
