# Generated by Django 4.2.3 on 2023-12-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0031_alter_book_category_alter_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('it', 'Italian'), ('es', 'Spanish'), ('bo', 'Tibetan'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('en', 'English'), ('fr', 'French')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
