# Generated by Django 4.2.3 on 2023-12-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peykhangApi', '0032_remove_book_summary_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non Fiction')], default='fiction', help_text='Select the book category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('bo', 'Tibetan'), ('zh', 'Chinese'), ('es', 'Spanish'), ('hi', 'Hindi'), ('en', 'English'), ('it', 'Italian'), ('fr', 'French')], default='tibetan', help_text='Selekc the book language'),
        ),
    ]
